#pragma once

#ifndef TRILOGY_NETWORKING_FEATURE_NICKGEN_H
#define TRILOGY_NETWORKING_FEATURE_NICKGEN_H

#include <common.hpp>

#include <memory/memory.hpp>
#include <random>

#define FEATURE_NICKGEN_SIZE_NICKNAMES 1893

namespace networking::features {
	class c_feature_nickgen : public c_singleton<c_feature_nickgen> {
	private:
		const char* m_random_nicknames[FEATURE_NICKGEN_SIZE_NICKNAMES] = {
			"Abash", "Abide", "Able", "Abund", "Accur", "Adept", "Admin", "Adore", "Adorn", "Adust", "Adult", "Adust", "Aegis",
			"Afire", "Afoot", "Again", "Agile", "Agree", "Aided", "Aimly", "Alive", "Aloof", "Aloud", "Amain", "Amaze", "Ample",
			"Amuck", "Angry", "Ankle", "Antic", "Apart", "Apple", "Apply", "Aptly", "Argue", "Arid", "Arose", "Array", "Arriv",
			"Assai", "Assay", "Assid", "Atoll", "Attic", "Audad", "Awake", "Aware", "Away", "Awoke", "Awry", "Babel", "Back",
			"Badge", "Bagel", "Baker", "Baldy", "Balky", "Balls", "Bandy", "Bang", "Baron", "Bash", "Bawdy", "Beady", "Beamy",
			"Beard", "Beast", "Beery", "Beige", "Belay", "Belly", "Belch", "Belga", "Bench", "Bendy", "Bent", "Beret", "Berry",
			"Beryl", "Beset", "Besot", "Bevel", "Bezel", "Bible", "Bigot", "Bijou", "Biker", "Bilge", "Billy", "Bimbo", "Binal",
			"Birch", "Birdy", "Bison", "Black", "Blanc", "Blaze", "Bleak", "Blend", "Bless", "Blind", "Bloat", "Block", "Blond",
			"Blood", "Bloom", "Bluff", "Blunt", "Blush", "Boast", "Bogus", "Boils", "Boldy", "Bonds", "Boned", "Bongo", "Bonny",
			"Bored", "Bound", "Brain", "Brave", "Brawn", "Bread", "Break", "Breve", "Bride", "Brief", "Brisk", "Broad", "Broke",
			"Brown", "Brusk", "Brush", "Bryce", "Bucks", "Bulge", "Bully", "Bumpy", "Bunch", "Bunny", "Burnt", "Burst", "Bushy",
			"Butch", "Butte", "Butyl", "Bylaw", "Cabin", "Cable", "Cacao", "Cadge", "Caged", "Cairn", "Calve", "Camel", "Candy",
			"Canes", "Canon", "Canto", "Caper", "Caput", "Cardy", "Cargo", "Carob", "Carve", "Casey", "Casky", "Caste", "Cater",
			"Catty", "Cavil", "Cedar", "Celts", "Cents", "Champ", "Chaos", "Chary", "Chase", "Cheap", "Check", "Cheek", "Cheer",
			"Chela", "Chert", "Chest", "Chews", "Chill", "Chimp", "Chirk", "Chirp", "Chose", "Chuck", "Chump", "Churl", "Churn",
			"Cinch", "Clack", "Clang", "Clank", "Clash", "Clasp", "Claws", "Cleft", "Clepe", "Click", "Cliff", "Clime", "Clung",
			"Clink", "Clock", "Clomp", "Clone", "Cluck", "Clump", "Cling", "Crank", "Crash", "Crawl", "Creep", "Crisp", "Crowd",
			"Crown", "Crumb", "Crush", "Cryad", "Cryed", "Cryer", "Cubic", "Culch", "Cupid", "Curet", "Curia", "Curry", "Cussy",
			"Cutis", "Cymar", "Cymes", "Cynic", "Cysts", "Cyton", "Dabby", "Daily", "Dairy", "Daisy", "Dally", "Dandy", "Dared",
			"Dated", "Deady", "Deave", "Decry", "Deedy", "Deept", "Delve", "Denis", "Denys", "Deray", "Derby", "Desay", "Desir",
			"Desly", "Deter", "Dexys", "Dials", "Dicey", "Didst", "Dight", "Dilly", "Dimer", "Dimly", "Dinar", "Dints", "Direr",
			"Dirts", "Dirty", "Disco", "Ditto", "Diver", "Divet", "Divot", "Dobby", "Doddy", "Dodge", "Dolce", "Dolly", "Doomy",
			"Dopey", "Dopys", "Dorky", "Dorps", "Dotty", "Dowry", "Dozen", "Drape", "Dress", "Dribs", "Drier", "Drift", "Drips",
			"Drugs", "Drupe", "Dryer", "Duads", "Dubos", "Ducks", "Ducky", "Duell", "Duels", "Dukes", "Dully", "Dulse", "Dumbs",
			"Dummy", "Dumps", "Dumpy", "Duple", "Dural", "Duras", "Dures", "Durns", "Durst", "Durst", "Dusky", "Dusty", "Duter",
			"Dyads", "Eadie", "Eager", "Early", "Earth", "Eater", "Eerie", "Elate", "Elfin", "Emlin", "Empty", "Enact", "Enfix",
			"Enfys", "Enemy", "Enfar", "Enfix", "Enfun", "Ensky", "Ensky", "Entad", "Enter", "Entry", "Enure", "Enweb", "Enzym",
			"Equal", "Erose", "Erode", "Erses", "Ershy", "Ersit", "Erupt", "Erxes", "Ethyl", "Ewers", "Ewigy", "Exact", "Exalt",
			"Exams", "Exalt", "Exept", "Expat", "Extra", "Exude", "Exuls", "Exult", "Exurb", "Eyass", "Eyren", "Eyrie", "Eyrir",
			"Fable", "Facer", "Facto", "Fader", "Fadge", "Fados", "Fairs", "Fairy", "False", "Fames", "Fancy", "Fanny", "Fards",
			"Farer", "Fares", "Farms", "Fancy", "Farey", "Faros", "Farrs", "Farts", "Fascy", "Fashy", "Fasts", "Fatly", "Faulk",
			"Fault", "Faulx", "Fauna", "Fause", "Fauve", "Favas", "Favel", "Faves", "Favos", "Fawny", "Faxed", "Fayer", "Faysy",
			"Fears", "Feast", "Feaze", "Fecer", "Feder", "Feder", "Fedes", "Feeds", "Fegar", "Fella", "Felly", "Felon", "Felty",
			"Femme", "Feral", "Feres", "Ferms", "Fermy", "Ferns", "Ferrt", "Ferus", "Ferve", "Fervy", "Fessy", "Fests", "Fetas",
			"Fetor", "Fetus", "Feuds", "Feuar", "Feuds", "Feued", "Feuks", "Fezzy", "Fiche", "Ficus", "Fidly", "Fidos", "Fiefs",
			"Fiery", "Fifed", "Fifer", "Fifes", "Fifty", "Figos", "Figgy", "Fight", "Figul", "Figue", "Filmy", "Filos", "Fimbe",
			"Fines", "Finos", "Firry", "First", "Firth", "Fishy", "Fisks", "Fisks", "Fisty", "Fitch", "Fiver", "Fives", "Fixes",
			"Fixin", "Fixup", "Fizzs", "Flabs", "Flack", "Flaff", "Flagy", "Flair", "Flake", "Flamy", "Flang", "Flans", "Flaps",
			"Flary", "Flask", "Flate", "Flats", "Flawn", "Flaws", "Flawy", "Flaxy", "Flawn", "Flaws", "Flawy", "Flaxy", "Flays",
			"Fleam", "Fleay", "Fleck", "Fleep", "Fleet", "Fleme", "Flemy", "Flens", "Flesh", "Flety", "Fleur", "Flick", "Flied",
			"Flier", "Flies", "Flimp", "Flind", "Flint", "Flips", "Flisk", "Flite", "Flock", "Flogs", "Floos", "Flops", "Flora",
			"Flore", "Flory", "Flout", "Flowk", "Flown", "Flows", "Floys", "Flubs", "Flued", "Flues", "Flued", "Fluke", "Fluky",
			"Flume", "Flump", "Flunk", "Flurry", "Flusk", "Fluxs", "Flype", "Flyte", "Foams", "Foamy", "Focal", "Fogie", "Foist",
			"Folds", "Foley", "Folks", "Folly", "Folts", "Fomes", "Fonze", "Fools", "Foosh", "Foots", "Foppy", "Forbs", "Forby",
			"Force", "Fordy", "Forfex", "Forge", "Forle", "Forms", "Formy", "Forts", "Forve", "Fouls", "Found", "Fourm", "Fouts",
			"Fowls", "Fowth", "Foxes", "Frabs", "Fraid", "Frail", "Frams", "Frams", "Frank", "Fraps", "Fraps", "Frayn", "Frays",
			"Freak", "Frems", "Fremy", "French", "Frere", "Frerk", "Fresh", "Frets", "Frett", "Fretz", "Fribs", "Frict", "Fried",
			"Frier", "Fries", "Frith", "Fritz", "Frizz", "Frize", "Frock", "Froes", "Frogs", "Frond", "Frond", "Front", "Frosk",
			"Frost", "Froth", "Froze", "Frush", "Frust", "Fucal", "Fucus", "Fuddy", "Fudge", "Fugal", "Fugie", "Fugle", "Fugly",
			"Fugue", "Fuhry", "Fujis", "Fulls", "Fully", "Fumes", "Fumet", "Fundi", "Funds", "Fungo", "Funis", "Funks", "Funny",
			"Furzy", "Fusht", "Fusil", "Fussy", "Fuste", "Fusty", "Fuzed", "Fuzes", "Fuzzy", "Gable", "Gaddi", "Gadid", "Gadis",
			"Gaily", "Gains", "Gaits", "Gales", "Galls", "Gally", "Galon", "Gamin", "Ganef", "Ganey", "Gangs", "Ganky", "Gants",
			"Gapes", "Gapos", "Gappy", "Garda", "Gards", "Gared", "Gares", "Garks", "Garns", "Garse", "Garts", "Gated", "Gater",
			"Gates", "Gatun", "Gauds", "Gaudy", "Gault", "Gaums", "Gaunt", "Gaupy", "Gauze", "Gauzy", "Gavel", "Gawcy", "Gawds",
			"Gawks", "Gawky", "Gawps", "Gawsy", "Gazee", "Gazer", "Gazes", "Gecko", "Geeks", "Geeky", "Geeks", "Geese", "Geest",
			"Gelds", "Gelee", "Gelts", "Gemma", "Gemma", "Gemma", "Gemma", "Genal", "Genas", "Genes", "Gents", "Genty", "Genua",
			"Genus", "Geode", "Geord", "Gerah", "Gerbe", "Gerea", "Gerez", "Germs", "Gerns", "Gerry", "Gerts", "Gesny", "Gesso",
			"Gests", "Getas", "Getes", "Getup", "Gevah", "Geway", "Gewur", "Ghana", "Ghees", "Ghess", "Ghobs", "Ghole", "Ghoom",
			"Ghoom", "Ghost", "Ghoul", "Ghyan", "Giard", "Giant", "Gibbs", "Giber", "Gibus", "Giddy", "Giffs", "Gifts", "Gifty",
			"Gigot", "Gigue", "Gilda", "Giles", "Gilga", "Gilts", "Gimel", "Gimpy", "Gimpy", "Gimps", "Ginns", "Ginny", "Gippy",
			"Gipps", "Gipsy", "Girly", "Girns", "Girny", "Girrs", "Girts", "Girza", "Gisks", "Gismo", "Gisms", "Gists", "Given",
			"Giver", "Gives", "Givin", "Gjess", "Gleam", "Glebe", "Gleds", "Gleen", "Glens", "Gless", "Gleye", "Gleys", "Glide",
			"Glime", "Glins", "Glint", "Glisk", "Glitz", "Gloam", "Gloat", "Globe", "Globs", "Gloge", "Glogg", "Gloms", "Gloom",
			"Glopy", "Glops", "Glory", "Gloss", "Gloze", "Gluck", "Glued", "Gluey", "Gluer", "Glues", "Gluey", "Gluge", "Glugs",
			"Glume", "Glums", "Glump", "Glunt", "Glure", "Gluts", "Gluzz", "Gnarl", "Gnarr", "Gnars", "Gnash", "Gnats", "Gnawy",
			"Gneis", "Gnide", "Gnite", "Gnoff", "Gnome", "Gnuks", "Goads", "Goafs", "Goals", "Goary", "Goats", "Goaty", "Goave",
			"Goban", "Gobos", "Gobur", "Godam", "Godet", "Godly", "Godon", "Godot", "Godun", "Goers", "Goffa", "Gogos", "Goide",
			"Going", "Goits", "Goixe", "Gojim", "Golfs", "Golly", "Goloe", "Golos", "Golpe", "Golps", "Gomal", "Gomas", "Gombo",
			"Gomey", "Gomez", "Gonak", "Gonch", "Gonek", "Goney", "Gongs", "Gonys", "Gooda", "Goodi", "Goodo", "Goods", "Goody",
			"Gooks", "Gooky", "Gools", "Goons", "Goony", "Goose", "Goosy", "Goped", "Gorak", "Gorah", "Goral", "Goran", "Gorch",
			"Gorde", "Gords", "Goree", "Gorey", "Gores", "Gorfs", "Gorge", "Gorgy", "Gorky", "Gorma", "Gorne", "Gorny", "Gorse",
			"Gorsy", "Gorza", "Gotha", "Gothy", "Gouar", "Goumi", "Goura", "Gouse", "Gouty", "Gouze", "Gowdy", "Gowan", "Gowdy",
			"Gowks", "Gowns", "Gowts", "Goyal", "Goyle", "Goysn", "Graal", "Grabs", "Grace", "Gracy", "Grads", "Graff", "Graft",
			"Grags", "Grail", "Grain", "Gramp", "Gramp", "Grana", "Grand", "Grant", "Grans", "Grapt", "Grare", "Grass", "Grate",
			"Grave", "Gravy", "Grays", "Graze", "Greap", "Great", "Greed", "Grees", "Greet", "Gregg", "Grego", "Greps", "Gress",
			"Greta", "Greys", "Greza", "Grief", "Griem", "Gries", "Grift", "Grigs", "Grill", "Grime", "Grimy", "Grind", "Gring",
			"Gripe", "Grips", "Gripy", "Grips", "Grisy", "Grith", "Gritt", "Groan", "Grobs", "Groce", "Grock", "Grody", "Groff",
			"Grogs", "Grois", "Groms", "Gronk", "Groom", "Groot", "Gross", "Grosz", "Grote", "Grots", "Group", "Grouse", "Grovy",
			"Groze", "Grozy", "Grube", "Grubs", "Gruff", "Grugq", "Gruze", "Guaco", "Guaka", "Gualo", "Guana", "Guane", "Guano",
			"Guans", "Guara", "Guars", "Guava", "Guaya", "Guaza", "Guaze", "Gubby", "Gubbu", "Gubus", "Gucks", "Gucks", "Gudef",
			"Gudes", "Gudge", "Guele", "Guele", "Gueri", "Guern", "Guers", "Guess", "Guest", "Gueve", "Guffy", "Guffs", "Gugal",
			"Guide", "Guild", "Guile", "Guily", "Guill", "Guils", "Guilt", "Guims", "Guine", "Guins", "Guise", "Guize", "Gular",
			"Gulch", "Gulfs", "Gulfy", "Gulge", "Gulks", "Gulky", "Gulli", "Gulls", "Gully", "Gulph", "Gulph", "Gulps", "Gulpy",
			"Gulve", "Gulze", "Gumby", "Gumma", "Gummy", "Gumps", "Gumpy", "Gumps", "Gumpy", "Gunar", "Gunet", "Gunja", "Gunky",
			"Gunny", "Gunny", "Gurda", "Gurds", "Gurgo", "Gurid", "Gurks", "Gurle", "Gurly", "Gurks", "Gurty", "Gurns", "Gurps",
			"Gurry", "Gurse", "Gurts", "Gurts", "Gurty", "Gurus", "Gurza", "Gurzi", "Gushi", "Gushy", "Gusle", "Gusli", "Gusse",
			"Gusts", "Gusty", "Gutka", "Gutsy", "Gutta", "Gutte", "Gutti", "Gutty", "Guyed", "Guzer", "Guzle", "Guzzi", "Gyald",
			"Gyali", "Gybed", "Gybes", "Gyeld", "Gymps", "Gynae", "Gymps", "Gynie", "Gyral", "Gyres", "Gyrus", "Gytes", "Gyved",
			"Gyves", "Gyving", "Gyzz", "Haafs", "Haars", "Habab", "Haban", "Habbe", "Habit", "Hable", "Hably", "Habre", "Hacek",
			"Haces", "Hacey", "Hacks", "Hacky", "Hadad", "Hadal", "Hadda", "Hadji", "Hades", "Hadid", "Hadji", "Hadum", "Hadze",
			"Haeck", "Haems", "Haere", "Hafar", "Hafer", "Hafiz", "Hafts", "Hagan", "Hager", "Hague", "Hagvy", "Haick", "Haida",
			"Haigh", "Haine", "Hains", "Haith", "Haiti", "Haits", "Haity", "Haize", "Hajee", "Hajis", "Hakan", "Hakim", "Halch",
			"Halec", "Haled", "Haler", "Hales", "Haley", "Halfa", "Halfy", "Hali", "Halim", "Halin", "Halis", "Halke", "Halma",
			"Halms", "Halog", "Halos", "Halot", "Halti", "Halts", "Halty", "Hamao", "Hamal", "Hamas", "Hamby", "Hamed", "Hamee",
			"Hamer", "Hames", "Hamid", "Hamon", "Hamra", "Hamsa", "Hamza", "Hance", "Handa", "Hands", "Handy", "Haned", "Hanes",
			"Hanfs", "Hanga", "Hangs", "Hanki", "Hanky", "Hanks", "Hanry", "Hansa", "Hanse", "Hanta", "Hants", "Hanus", "Hanze",
			"Hanza", "Hanza", "Hanzo", "Haply", "Happs", "Happy", "Haque", "Harbi", "Hards", "Hardy", "Hared", "Harem", "Haren",
			"Hares", "Haret", "Harks", "Harps", "Harrs", "Harse", "Harsh", "Harti", "Harts", "Harum", "Harut", "Harve", "Harza",
			"Hasan", "Hasan", "Hasca", "Hasen", "Hasky", "Hasps", "Haste", "Hasty", "Hasup", "Hasup", "Haswe", "Hatch", "Hatha",
			"Hated", "Haten", "Hater", "Hates", "Hatha", "Hathe", "Hatho", "Hathi", "Haths", "Hatie", "Hatin", "Hatky", "Hator",
			"Hatsy", "Haugh", "Hauks", "Haunt", "Haute", "Hauyn", "Havas", "Haven", "Haver", "Haves", "Havid", "Havoc", "Havot",
			"Haweb", "Hawes", "Hawgs", "Hawks", "Hawky", "Hawms", "Hawny", "Hawse", "Hawss", "Hawth", "Haxon", "Hazel", "Hazen",
			"Hazle", "Hazus", "Hdive", "Heada", "Heads", "Heady", "Heald", "Heale", "Healy", "Heame", "Heapo", "Heaps", "Heapy",
			"Hearm", "Heard", "Heare", "Heary", "Heard", "Heare", "Heart", "Hease", "Heast", "Heasy", "Heats", "Heaty", "Heave",
			"Heaze", "Heazy", "Hebby", "Hebes", "Hebri", "Hebry", "Hecht", "Hecky", "Heday", "Heddi", "Heddy", "Hedge", "Hedgy",
			"Hedir", "Hedis", "Hedra", "Hedry", "Heeds", "Heedy", "Heele", "Heely", "Heepo", "Heery", "Heeze", "Heezy", "Hefes",
			"Hefts", "Hefty", "Hegar", "Hegem", "Hegri", "Heias", "Heigh", "Heihs", "Heiho", "Heiis", "Heiks", "Heila", "Heile",
			"Heils", "Heime", "Heine", "Heins", "Heinz", "Heirs", "Heisa", "Heise", "Heish", "Heisk", "Heist", "Heits", "Heity",
			"Heius", "Heium", "Heize", "Heizo", "Heizo", "Hejar", "Hejaz", "Hejin", "Hekel", "Heker", "Helah", "Heldi", "Helen",
			"Helfa", "Helfd", "Helfs", "Helve", "Helvy", "Helza", "Helzy", "Hemal", "Hemed", "Hemps", "Hempy", "Henad", "Hence",
			"Hends", "Henek", "Henge", "Hengi", "Hengo", "Hengs", "Henge", "Hengi", "Hengo", "Hengs", "Henia", "Henka", "Henna",
			"Henni", "Henny", "Henor", "Henri", "Hents", "Henty", "Hents", "Henty", "Henza", "Hepps", "Heppy", "Heppz", "Heral",
			"Herap", "Herat", "Herbs", "Herby", "Herbs", "Herby", "Hercs", "Herdz", "Herds", "Herdy", "Hered", "Herem", "Herer",
			"Herfs", "Herge", "Herig", "Herin", "Herip", "Heris", "Heriz", "Herke", "Hermi", "Hermi", "Herms", "Herne", "Heron",
			"Herou", "Herps", "Herry", "Hersh", "Herso", "Herta", "Hertz", "Herum", "Herve", "Hervo", "Herze", "Herzi", "Herzy",
			"Hesbi", "Hesco", "Hesel", "Hesle", "Hesly", "Hesse", "Hessi", "Hesta", "Hesty", "Hetal", "Hetts", "Hetty", "Hetun",
			"Heuau", "Heuch", "Heugh", "Hevah", "Heves", "Heway", "Hewer", "Hewes", "Hewed", "Hewen", "Hewer", "Hewes", "Hewit",
			"Hexad", "Hexam", "Hexes", "Hexyl", "Heyde", "Heygh", "Heyts", "Heyws", "Hibby", "Hicke", "Hicki", "Hicks", "Hiddy",
			"Hider", "Hides", "Hidke", "Hidro", "Hidry", "Hieck", "Hield", "Hield", "Hiels", "Hieth", "Hiffe", "Hiffs", "Hifne",
			"Hight", "Hilch", "Hilka", "Hilks", "Hilky", "Hills", "Hilms", "Hilmy", "Hilts", "Hilty", "Hilve", "Hilzy", "Himba",
			"Himbe", "Himbo", "Himer", "Himes", "Himly", "Hinds", "Hindy", "Hiney", "Hinge", "Hinna", "Hinny", "Hinst", "Hirai",
			"Hiree", "Hiren", "Hires", "Hirse", "Hirst", "Hirud", "Hirzi", "Hisda", "Hisco", "Hisea", "Hispa", "Hisse", "Hists",
			"Hitch", "Hitea", "Hitho", "Hitte", "Hivah", "Hivem", "Hiver", "Hives", "Hivet", "Hiwks", "Hiwls", "Hixes", "Hizen",
			"Hizik", "Hlave", "Hlayk", "Hlend", "Hlied", "Hlies", "Hlong", "Hlong", "Hlope", "Hlope", "Hlops", "Hlyde", "Hlyes",
			"Hlyun", "Hlyyn", "Hoagy", "Hoang", "Hoary", "Hoban", "Hobba", "Hobbe", "Hobbs", "Hobby", "Hobka", "Hobos", "Hobza",
			"Hocky", "Hocks", "Hocus", "Hocte", "Hocum", "Hocus", "Hocut", "Hocus", "Hocut", "Hodad", "Hodad", "Hoddy", "Hodga",
			"Hodge", "Hodgs", "Hodja", "Hodny", "Hodos", "Hodoy", "Hofus", "Hogal", "Hogan", "Hoggs", "Hogin", "Hogon", "Hogum",
			"Hogue", "Hogus", "Hogys", "Hohok", "Hohum", "Hoick", "Hoise", "Hoist", "Hokey", "Hoket", "Hokie", "Hokis", "Hokum",
			"Hokys", "Holey", "Holic", "Holks", "Holla", "Holli", "Holly", "Holms", "Holom", "Holos", "Holon", "Holts", "Holva",
			"Homan", "Homas", "Homay", "Homes", "Homey", "Homie", "Homos", "Homps", "Homra", "Homus", "Homys", "Honey", "Hongs",
			"Hongy", "Honks", "Honky", "Honra", "Honso", "Honys", "Honor", "Hooch", "Hoodi", "Hoods", "Hooey", "Hoofy", "Hooks",
			"Hooky", "Hoops", "Hoops", "Hoots", "Hoovy", "Hooze", "Hoozy", "Hopak", "Hopas", "Hopak", "Hopey", "Hoped", "Hopey",
			"Hoper", "Hopes", "Hophy", "Hopis", "Hoppy", "Hoppa", "Hoppy", "Horah", "Horas", "Horde", "Horda", "Horde", "Horim",
			"Horns", "Horny", "Horsa", "Horse", "Horsy", "Horvy", "Horyn", "Horza", "Horzy", "Hosey", "Hosel", "Hoses", "Hoshy",
			"Hoshy", "Hosoi", "Hossa", "Hosta", "Hosts", "Hosya", "Hotal", "Hotam", "Hotch", "Hotei", "Hotel", "Hoten", "Hoter",
			"Hotis", "Hotok", "Hoton", "Hotop", "Houar", "Houck", "Houda", "Houey", "Hough", "Hough", "Houle", "Hoult", "Hound",
			"Houng", "Hount", "Hours", "House", "Housy", "Houth", "Houtz", "Hovan", "Hovel", "Hoven", "Hover", "Hovey", "Howay",
			"Howdy", "Howea", "Howel", "Howes", "Howff", "Howff", "Howfs", "Howks", "Howls", "Howly", "Howse", "Howth", "Howve",
			"Howze", "Howzy", "Hoxha", "Hoyas", "Hoyen", "Hoyes", "Hoyne", "Hoyse", "Hozen", "Hozey", "Hozzy", "Huari", "Huarz",
			"Hubal", "Hubbs", "Huber", "Hubey", "Hubia", "Hubin", "Hubis", "Hucks", "Hudde", "Huddy", "Hudge", "Hudia", "Hudic",
			"Hudio", "Hudis", "Hudon", "Hudra", "Hudus", "Hudya", "Huebs", "Huels", "Huern", "Huerz", "Huess", "Huetz", "Huffy",
			"Huffs", "Hugan", "Hugar", "Hugel", "Huger", "Hughy", "Hugos", "Hugys", "Huhis", "Huhum", "Huias", "Huich", "Huijn",
			"Huijs", "Huiky", "Huksy", "Hulah", "Hulda", "Hulic", "Hulja", "Hulki", "Hulks", "Hulme", "Hulms", "Hulon", "Hulor",
			"Hulps", "Hulpy", "Hults", "Hulve", "Hulze", "Hulzy", "Human", "Humbe", "Humby", "Humee", "Humer", "Humor", "Humps",
			"Humpy", "Humpy", "Hunch", "Hunks", "Hunky", "Hunne", "Hunty", "Hunza", "Hunzy", "Hupka", "Hural", "Huran", "Hurat",
			"Hurat", "Hurdy", "Hurel", "Hurin", "Hurry", "Hurth", "Hurty", "Hurva" };

	public:
		std::string get_nickname();
	};
}

#endif
